# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

#gems
plugins: [jekyll-paginate]

# Setup
title:           Momex
name:            Momex
description: HD, Electronics and more.
url:              http://momex.github.io
newbaseurl: /

author:
  name:           'Xavier Morales'
  url:            https://momex.github.io
  email:          momexcat@gmail.com

paginate:         5

# Custom vars
version:          0.0.1
excerpt_separator: <!--more-->
google_verify: PzxwYKxfaTiI1Pl8QCOSc7mS06CjQeyBXlAy71-QZpY
github:
  repo:           https://github.com/momex/momex.github.io.git

trans:
  ca:
    desc: "Projectes d'electrònica relacionats amb Harley Davidson i d'altres de caire DIY domèstic."
    home: "Inici"
    about: "Sobre mi"
    related: "Posts similars amb la categoria"
    search: "Buscar a momex.github.io"
    arxiu: "Arxiu"
    cont: "Contacte"
    ghpro: "Projecte web GitHub"
    tachoHD: "Tacòmetre Harley Davidson"
    tagline: "Projectes d'electrònica i altres"
    seguiu: "...Seguiu llegint"
  en:
    desc: "Electronic projects related to Harley Davidson and domestic DYI.                         "
    home: "Home"
    about: "About"
    related: "Related Posts with similar category"
    search: "Search in momex.github.io:"
    arxiu: "Archive"
    cont: "Contact"
    ghpro: "GitHub project"
    tachoHD: "Tachometer Harley Davidson"
    tagline: "Electronic projects and others"
    seguiu: "...Read more"
